# Generated by Django 6.1 on 2026-08-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('family', models.CharField(choices=[('trumpet', 'Trumpet'), ('euphonium', 'Euphonium'), ('trombone', 'Trombone'), ('cornet', 'Cornet'), ('tuba', 'Tuba'), ('flugelhorn', 'Flugelhorn'), ('other', 'Other')], max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Flexible spec key/value pairs, e.g. {"bore": "0.459\\"", "bell_material": "Yellow brass", "finish": "Lacquer"}')),
                ('finish_options', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Lacquer, Silver plate, Raw brass'", max_length=300)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='instruments/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="ISO country code, e.g. 'US', 'DE', 'JP'.", max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('family', models.CharField(choices=[('trumpet', 'Trumpet'), ('euphonium', 'Euphonium'), ('trombone', 'Trombone'), ('cornet', 'Cornet'), ('tuba', 'Tuba'), ('flugelhorn', 'Flugelhorn'), ('other', 'Other')], max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('body', models.TextField(help_text='Rich text (HTML) — use the CKEditor field if installed.')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instruments/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.instrument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('families_carried', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Trumpet, Trombone'", max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='catalog.region')),
            ],
            options={
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='catalog.series'),
        ),
    ]
