# Generated by Django 6.1 on 2026-09-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('family', models.CharField(choices=[('trumpet', 'Trumpet'), ('euphonium', 'Euphonium'), ('trombone', 'Trombone'), ('cornet', 'Cornet'), ('tuba', 'Tuba'), ('flugelhorn', 'Flugelhorn'), ('other', 'Other')], max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='series',
        ),
        migrations.RemoveField(
            model_name='instrumentimage',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='SitePage',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentImage',
        ),
    ]
