# Generated by Django 6.1 on 2026-09-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dealerregistration_product_remove_dealer_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.CharField(choices=[('trumpet', 'Trumpet'), ('euphonium', 'Euphonium'), ('trombone', 'Trombone'), ('cornet', 'Cornet'), ('tuba', 'Tuba'), ('flugelhorn', 'Flugelhorn'), ('saxophone', 'Saxophone'), ('side-drum', 'Side drum'), ('bass-drum', 'Bass drum'), ('other', 'Other')], max_length=20),
        ),
    ]
