# Generated by Django 6.1 on 2026-09-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerregistration',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dealerregistration',
            name='message',
        ),
        migrations.RemoveField(
            model_name='dealerregistration',
            name='website',
        ),
        migrations.AddField(
            model_name='dealerregistration',
            name='gst_number',
            field=models.CharField(default='', max_length=15, verbose_name='GST number'),
        ),
    ]
